#!perl
use strict;
use warnings;
use CPAN::Mirror::Tiny::Server;

warn "WARN: This script is deprecated, use `cpan-mirror-tiny server` instead.\n";
CPAN::Mirror::Tiny::Server->start(@ARGV);

__END__

=head1 NAME

cpan-mirror-tiny-server - run http server for your darkpan

=head1 SYNOPSIS

  $ cpan-mirror-tiny-server

=head1 DESCRIPTION

This script is deprecated, use C<cpan-mirror-tiny server> instead.

=cut

